---
driver:
  name: docker

ansible:
  executor:
    backend: ansible-playbook

provisioner:
  name: ansible
  config_options:
    defaults:
      # Uses the absolute path of your project to safely find the roles folder
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles
  inventory:
    group_vars:
      all:
        tenant_cred_registry_password: "${tenant_cred_registry_password}" # Placeholder: Should be retrieve dynamically during play
        tenant_cred_repo_password: "${tenant_cred_repo_password}" # Placeholder: Should be retrieve dynamically during play
        s_preprod_cd_pipeline_sample_tarball_url: "${sample_tarball_url}"
        s_preprod_cd_pipeline_sample_s3_secret_api_key: "${sample_s3_secret_api_key}"
        s_preprod_cd_pipeline_sample_s3_secret_api_secret: "${sample_s3_secret_api_secret}"
        s_preprod_cd_pipeline_release_bundle_remote_path: "${sample_release_bundle_remote_path}"
  env:
    SFTP_HOST: "172.28.0.10"
    SFTP_USERNAME: "foo"
    SFTP_PASSWORD: "pass"
    KEYCLOAK_CLIENT_ID: "not-used-yet"
    KEYCLOAK_CLIENT_SECRET: "not-used-yet"
    KEYCLOAK_TOKEN_URL: "https://auth.not.used.yet/realms/loki/protocol/openid-connect/token"
    CD_DB_GIT_REPO_URL: ${cd_db_git_repo_url}
    CD_DB_ADMIN_USERNAME: ${cd_db_admin_username}
    CD_DB_ADMIN_PASSWORD: ${cd_db_admin_password}
    LOKI_ENDPOINT: "https://loki.not.used.yet/loki/api/v1/push"

platforms:
  - name: sftp-srv
    image: atmoz/sftp
    command: "foo:pass:::upload"
    privileged: false
    networks:
      - name: molecule-net
        ipv4_address: 172.28.0.10
  - name: instance
    image: ghcr.io/yangjie500/cd_cluster.cd_pipeline_common:1.2.0
    privileged: true
    networks:
      - name: molecule-net
        ipv4_address: 172.28.0.11
    pre_build_image: true

scenario:
  name: s_preprod_cd_pipeline
  test_sequence:
    - create
    - prepare
    - converge
    - verify
    - destroy
